# Generated by Django 5.1.2 on 2024-11-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="textbook",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="textbook_images/"
            ),
        ),
    ]
