# Generated by Django 5.1.5 on 2025-01-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0004_textbook_created_at_textbook_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="textbook",
            name="phone_contact",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="textbook",
            name="telegram_contact",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="textbook",
            name="viber_contact",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="textbook",
            name="whatsapp_contact",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
